#ifndef GENERATED_ASN1SCC_a_H
#define GENERATED_ASN1SCC_a_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint BUFFER_LENGTH_TYPE;


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2);

#define ERR_BUFFER_LENGTH_TYPE		1  /*(0..100)*/
flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode);

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal);

#define BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define BUFFER_LENGTH_TYPE_REQUIRED_BITS_FOR_ACN_ENCODING        7

#define ERR_ACN_ENCODE_BUFFER_LENGTH_TYPE		4  /**/

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_BUFFER_LENGTH_TYPE		5  /**/
flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PayloadData --------------------------------------------*/
typedef asn1SccSint PayloadData_int_field;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData_buffer;

typedef struct {
    PayloadData_int_field int_field;
    PayloadData_buffer buffer;

} PayloadData;

flag PayloadData_int_field_Equal(const PayloadData_int_field* pVal1, const PayloadData_int_field* pVal2);

flag PayloadData_buffer_Equal(const PayloadData_buffer* pVal1, const PayloadData_buffer* pVal2);

flag PayloadData_Equal(const PayloadData* pVal1, const PayloadData* pVal2);

#define ERR_PAYLOADDATA_INT_FIELD		6  /*(-2147483648..2147483647)*/
flag PayloadData_int_field_IsConstraintValid(const PayloadData_int_field* pVal, int* pErrCode);

#define ERR_PAYLOADDATA_BUFFER		11  /*(SIZE(0..100))*/
flag PayloadData_buffer_IsConstraintValid(const PayloadData_buffer* pVal, int* pErrCode);

#define ERR_PAYLOADDATA		16  /**/
flag PayloadData_IsConstraintValid(const PayloadData* pVal, int* pErrCode);

void PayloadData_int_field_Initialize(PayloadData_int_field* pVal);
void PayloadData_buffer_Initialize(PayloadData_buffer* pVal);
void PayloadData_Initialize(PayloadData* pVal);

#define PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING       104
#define PayloadData_REQUIRED_BITS_FOR_ACN_ENCODING        832
/*-- Header --------------------------------------------*/
typedef struct {

} Header;

flag Header_Equal(const Header* pVal1, const Header* pVal2);

#define ERR_HEADER		21  /**/
flag Header_IsConstraintValid(const Header* pVal, int* pErrCode);

void Header_Initialize(Header* pVal);

#define Header_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define Header_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDU --------------------------------------------*/
typedef struct {
    Header hdr;
    PayloadData payload;

} PDU;

flag PDU_Equal(const PDU* pVal1, const PDU* pVal2);

#define ERR_PDU		56  /**/
#define ERR_PDU_HDR_2		35  /**/
#define ERR_PDU_PAYLOAD_2		53  /**/
flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode);

void PDU_Initialize(PDU* pVal);

#define PDU_REQUIRED_BYTES_FOR_ACN_ENCODING       106
#define PDU_REQUIRED_BITS_FOR_ACN_ENCODING        848

#define ERR_ACN_ENCODE_PDU		59  /**/
#define ERR_ACN_ENCODE_PDU_HDR		33  /**/
#define ERR_ACN_ENCODE_PDU_HDR_VERSION		26  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED		60  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH		28  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD		51  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_INT_FIELD		41  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_BUFFER		46  /**/

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PDU		61  /**/
#define ERR_ACN_DECODE_PDU_HDR		34  /**/
#define ERR_ACN_DECODE_PDU_HDR_VERSION		27  /**/
#define ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH		29  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD		52  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_INT_FIELD		42  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_BUFFER		47  /**/
flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
