/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "a.h"


flag RGB_t_r_Equal(const RGB_t_r* pVal1, const RGB_t_r* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag RGB_t_g_Equal(const RGB_t_g* pVal1, const RGB_t_g* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag RGB_t_b_Equal(const RGB_t_b* pVal1, const RGB_t_b* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag RGB_t_opacity_Equal(const RGB_t_opacity* pVal1, const RGB_t_opacity* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag RGB_t_Equal(const RGB_t* pVal1, const RGB_t* pVal2)
{
	flag ret=TRUE;

    ret = RGB_t_r_Equal((&(pVal1->r)), (&(pVal2->r)));
    
    if (ret) {
        ret = RGB_t_g_Equal((&(pVal1->g)), (&(pVal2->g)));
        
        if (ret) {
            ret = RGB_t_b_Equal((&(pVal1->b)), (&(pVal2->b)));
            
            if (ret) {
                ret = (pVal1->exist.opacity == pVal2->exist.opacity);
                if (ret && pVal1->exist.opacity) {
                	ret = RGB_t_opacity_Equal((&(pVal1->opacity)), (&(pVal2->opacity)));
                }
            
            }
        
        }
    
    }

	return ret;

}

flag RGB_t_r_IsConstraintValid(const RGB_t_r* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_RGB_T_R;

	return ret;
}

flag RGB_t_g_IsConstraintValid(const RGB_t_g* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_RGB_T_G;

	return ret;
}

flag RGB_t_b_IsConstraintValid(const RGB_t_b* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_RGB_T_B;

	return ret;
}

flag RGB_t_opacity_IsConstraintValid(const RGB_t_opacity* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_RGB_T_OPACITY;

	return ret;
}

flag RGB_t_IsConstraintValid(const RGB_t* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = RGB_t_r_IsConstraintValid((&(pVal->r)), pErrCode);
    if (ret) {
        ret = RGB_t_g_IsConstraintValid((&(pVal->g)), pErrCode);
        if (ret) {
            ret = RGB_t_b_IsConstraintValid((&(pVal->b)), pErrCode);
            if (ret) {
                if (pVal->exist.opacity) {
                	ret = RGB_t_opacity_IsConstraintValid((&(pVal->opacity)), pErrCode);
                }
            }   /*COVERAGE_IGNORE*/
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void RGB_t_r_Initialize(RGB_t_r* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void RGB_t_g_Initialize(RGB_t_g* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void RGB_t_b_Initialize(RGB_t_b* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void RGB_t_opacity_Initialize(RGB_t_opacity* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}
void RGB_t_Initialize(RGB_t* pVal)
{
	(void)pVal;


	/*set r */
	RGB_t_r_Initialize((&(pVal->r)));
	/*set g */
	RGB_t_g_Initialize((&(pVal->g)));
	/*set b */
	RGB_t_b_Initialize((&(pVal->b)));
	/*set opacity */
	pVal->exist.opacity = 1;
	RGB_t_opacity_Initialize((&(pVal->opacity)));
}

flag RGB_t_ACN_Encode(const RGB_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? RGB_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,pVal->exist.opacity);
	    if (ret) {
	        /*Encode r */
	        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->r, 0, 255);
	        if (ret) {
	            /*Encode g */
	            BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->g, 0, 255);
	            if (ret) {
	                /*Encode b */
	                BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->b, 0, 255);
	                if (ret) {
	                    /*Encode opacity */
	                    if (pVal->exist.opacity) {
	                    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, pVal->opacity, 0, 255);
	                    }
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag RGB_t_ACN_Decode(RGB_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	flag opacity_exist;

	ret = BitStream_ReadBit(pBitStrm, &opacity_exist);
	pVal->exist.opacity = opacity_exist == 0 ? 0 : 1;
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_RGB_T;
	if (ret) {
	    /*Decode r */
	    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->r)), 0, 255);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_RGB_T_R;
	    if (ret) {
	        /*Decode g */
	        ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->g)), 0, 255);
	        *pErrCode = ret ? 0 : ERR_ACN_DECODE_RGB_T_G;
	        if (ret) {
	            /*Decode b */
	            ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->b)), 0, 255);
	            *pErrCode = ret ? 0 : ERR_ACN_DECODE_RGB_T_B;
	            if (ret) {
	                /*Decode opacity */
	                if (pVal->exist.opacity) {
	                	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(pVal->opacity)), 0, 255);
	                	*pErrCode = ret ? 0 : ERR_ACN_DECODE_RGB_T_OPACITY;
	                }
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && RGB_t_IsConstraintValid(pVal, pErrCode);
}


flag PDU_Equal(const PDU* pVal1, const PDU* pVal2)
{
	flag ret=TRUE;

    ret = RGB_t_Equal((&(pVal1->rgb)), (&(pVal2->rgb)));

	return ret;

}

flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = RGB_t_IsConstraintValid((&(pVal->rgb)), pErrCode);

	return ret;
}

void PDU_Initialize(PDU* pVal)
{
	(void)pVal;


	/*set rgb */
	RGB_t_Initialize((&(pVal->rgb)));
}

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? PDU_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode rgb */
	    /*open new scope to declare some variables*/
	    {
	    	/*encode to a temporary bitstream*/
	    	static byte arr[RGB_t_REQUIRED_BYTES_FOR_ACN_ENCODING];
	    	BitStream bitStrm;
	    	BitStream_Init(&bitStrm, arr, sizeof(arr));

	    	ret = RGB_t_ACN_Encode((&(pVal->rgb)), &bitStrm, pErrCode, FALSE);
	    	if (ret) {
	    		int nCount = bitStrm.currentBit == 0 ? bitStrm.currentByte : (bitStrm.currentByte + 1);
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount, 4, 5);
	    		ret = BitStream_EncodeOctetString_no_length(pBitStrm, arr, nCount);

	    	}
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	/*Decode rgb */
	/*open new scope to declare some variables*/
	{
		/*decode to a temporary bitstream*/
		static byte arr[RGB_t_REQUIRED_BYTES_FOR_ACN_ENCODING];
		BitStream bitStrm;
		BitStream_Init(&bitStrm, arr, sizeof(arr));

		asn1SccSint nCount;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 4, 5);
		if (ret) {
			ret = BitStream_DecodeOctetString_no_length(pBitStrm, arr, (int)nCount);
		}

		if (ret) {
			ret = RGB_t_ACN_Decode((&(pVal->rgb)), &bitStrm, pErrCode);
		}
	}

    return ret && PDU_IsConstraintValid(pVal, pErrCode);
}


