#ifndef GENERATED_ASN1SCC_a_H
#define GENERATED_ASN1SCC_a_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


/*-- RGB_t --------------------------------------------*/
typedef asn1SccUint RGB_t_r;

typedef asn1SccUint RGB_t_g;

typedef asn1SccUint RGB_t_b;

typedef asn1SccUint RGB_t_opacity;

typedef struct {
    unsigned long opacity:1;
} RGB_t_exist;
typedef struct {
    RGB_t_r r;
    RGB_t_g g;
    RGB_t_b b;
    RGB_t_opacity opacity;

    RGB_t_exist exist;

} RGB_t;

flag RGB_t_r_Equal(const RGB_t_r* pVal1, const RGB_t_r* pVal2);

flag RGB_t_g_Equal(const RGB_t_g* pVal1, const RGB_t_g* pVal2);

flag RGB_t_b_Equal(const RGB_t_b* pVal1, const RGB_t_b* pVal2);

flag RGB_t_opacity_Equal(const RGB_t_opacity* pVal1, const RGB_t_opacity* pVal2);

flag RGB_t_Equal(const RGB_t* pVal1, const RGB_t* pVal2);

#define ERR_RGB_T_R		1  /*(0 .. 255)*/
flag RGB_t_r_IsConstraintValid(const RGB_t_r* pVal, int* pErrCode);

#define ERR_RGB_T_G		6  /*(0 .. 255)*/
flag RGB_t_g_IsConstraintValid(const RGB_t_g* pVal, int* pErrCode);

#define ERR_RGB_T_B		11  /*(0 .. 255)*/
flag RGB_t_b_IsConstraintValid(const RGB_t_b* pVal, int* pErrCode);

#define ERR_RGB_T_OPACITY		16  /*(0 .. 255)*/
flag RGB_t_opacity_IsConstraintValid(const RGB_t_opacity* pVal, int* pErrCode);

#define ERR_RGB_T		21  /**/
flag RGB_t_IsConstraintValid(const RGB_t* pVal, int* pErrCode);

void RGB_t_r_Initialize(RGB_t_r* pVal);
void RGB_t_g_Initialize(RGB_t_g* pVal);
void RGB_t_b_Initialize(RGB_t_b* pVal);
void RGB_t_opacity_Initialize(RGB_t_opacity* pVal);
void RGB_t_Initialize(RGB_t* pVal);

#define RGB_t_REQUIRED_BYTES_FOR_ACN_ENCODING       5
#define RGB_t_REQUIRED_BITS_FOR_ACN_ENCODING        33

#define ERR_ACN_ENCODE_RGB_T		24  /**/
#define ERR_ACN_ENCODE_RGB_T_R		4  /**/
#define ERR_ACN_ENCODE_RGB_T_G		9  /**/
#define ERR_ACN_ENCODE_RGB_T_B		14  /**/
#define ERR_ACN_ENCODE_RGB_T_OPACITY		19  /**/

flag RGB_t_ACN_Encode(const RGB_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_RGB_T		25  /**/
#define ERR_ACN_DECODE_RGB_T_R		5  /**/
#define ERR_ACN_DECODE_RGB_T_G		10  /**/
#define ERR_ACN_DECODE_RGB_T_B		15  /**/
#define ERR_ACN_DECODE_RGB_T_OPACITY		20  /**/
flag RGB_t_ACN_Decode(RGB_t* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDU --------------------------------------------*/
typedef struct {
    RGB_t rgb;

} PDU;

flag PDU_Equal(const PDU* pVal1, const PDU* pVal2);

#define ERR_PDU		56  /**/
#define ERR_PDU_RGB_2		51  /**/
flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode);

void PDU_Initialize(PDU* pVal);

#define PDU_REQUIRED_BYTES_FOR_ACN_ENCODING       6
#define PDU_REQUIRED_BITS_FOR_ACN_ENCODING        41

#define ERR_ACN_ENCODE_PDU		59  /**/
#define ERR_ACN_ENCODE_PDU_RGB_2		54  /**/

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PDU		60  /**/
#define ERR_ACN_DECODE_PDU_RGB_2		55  /**/
flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
