/*  Code automatically generated by asn1scc tool (stg macro : printTestCaseFileBody) */

#include "test_case_001.h"

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>

#ifndef _MSC_VER
#include <sys/time.h>

#endif // _MSC_VER

#include "asn1crt.h"

#include "a_auto_tcs.h"

void test_case_ACN_000001(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000001");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set rgb */
    /*set r */
    tc_data.rgb.r = 0UL;
    /*set g */
    tc_data.rgb.g = 0UL;
    /*set b */
    tc_data.rgb.b = 0UL;
    /*set opacity */
    tc_data.rgb.exist.opacity = 1;
    tc_data.rgb.opacity = 0UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000001");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000001", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000001");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000001 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000001'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000002(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000002");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set rgb */
    /*set r */
    tc_data.rgb.r = 255UL;
    /*set g */
    tc_data.rgb.g = 255UL;
    /*set b */
    tc_data.rgb.b = 255UL;
    tc_data.rgb.exist.opacity = 0;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000002");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000002", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000002");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000002 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000002'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000003(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000003");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set rgb */
    /*set r */
    tc_data.rgb.r = 0UL;
    /*set g */
    tc_data.rgb.g = 0UL;
    /*set b */
    tc_data.rgb.b = 0UL;
    /*set opacity */
    tc_data.rgb.exist.opacity = 1;
    tc_data.rgb.opacity = 255UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000003");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000003", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000003");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000003 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000003'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000004(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000004");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set rgb */
    /*set r */
    tc_data.rgb.r = 255UL;
    /*set g */
    tc_data.rgb.g = 255UL;
    /*set b */
    tc_data.rgb.b = 255UL;
    tc_data.rgb.exist.opacity = 0;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000004");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000004", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000004");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000004 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000004'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000005(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000005");
    {
        // dummy statement used for calling init functions
        static RGB_t tmp0;
        RGB_t_r_Initialize((&(tmp0.r)));
        RGB_t_g_Initialize((&(tmp0.g)));
        RGB_t_b_Initialize((&(tmp0.b)));
        RGB_t_opacity_Initialize((&(tmp0.opacity)));
        RGB_t_Initialize((&(tmp0)));
    }

    static RGB_t tc_data; 
    /*set r */
    tc_data.r = 0UL;
    /*set g */
    tc_data.g = 0UL;
    /*set b */
    tc_data.b = 0UL;
    /*set opacity */
    tc_data.exist.opacity = 1;
    tc_data.opacity = 0UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000005");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("RGB_t/test_case_ACN_000005", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000005");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000005 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000005'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000006(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000006");
    {
        // dummy statement used for calling init functions
        static RGB_t tmp0;
        RGB_t_r_Initialize((&(tmp0.r)));
        RGB_t_g_Initialize((&(tmp0.g)));
        RGB_t_b_Initialize((&(tmp0.b)));
        RGB_t_opacity_Initialize((&(tmp0.opacity)));
        RGB_t_Initialize((&(tmp0)));
    }

    static RGB_t tc_data; 
    /*set r */
    tc_data.r = 255UL;
    /*set g */
    tc_data.g = 255UL;
    /*set b */
    tc_data.b = 255UL;
    tc_data.exist.opacity = 0;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000006");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("RGB_t/test_case_ACN_000006", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000006");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000006 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000006'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000007(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000007");
    {
        // dummy statement used for calling init functions
        static RGB_t tmp0;
        RGB_t_r_Initialize((&(tmp0.r)));
        RGB_t_g_Initialize((&(tmp0.g)));
        RGB_t_b_Initialize((&(tmp0.b)));
        RGB_t_opacity_Initialize((&(tmp0.opacity)));
        RGB_t_Initialize((&(tmp0)));
    }

    static RGB_t tc_data; 
    /*set r */
    tc_data.r = 0UL;
    /*set g */
    tc_data.g = 0UL;
    /*set b */
    tc_data.b = 0UL;
    /*set opacity */
    tc_data.exist.opacity = 1;
    tc_data.opacity = 255UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000007");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("RGB_t/test_case_ACN_000007", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000007");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000007 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000007' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000007' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000007' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000007'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000008(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000008");
    {
        // dummy statement used for calling init functions
        static RGB_t tmp0;
        RGB_t_r_Initialize((&(tmp0.r)));
        RGB_t_g_Initialize((&(tmp0.g)));
        RGB_t_b_Initialize((&(tmp0.b)));
        RGB_t_opacity_Initialize((&(tmp0.opacity)));
        RGB_t_Initialize((&(tmp0)));
    }

    static RGB_t tc_data; 
    /*set r */
    tc_data.r = 255UL;
    /*set g */
    tc_data.g = 255UL;
    /*set b */
    tc_data.b = 255UL;
    tc_data.exist.opacity = 0;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000008");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("RGB_t/test_case_ACN_000008", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = RGB_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000008");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000008 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000008' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000008' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000008' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000008'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}
