/*  Code automatically generated by asn1scc tool (stg macro : PrintATCRunner) */

#include "testsuite.h"

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>

#include "asn1crt.h"

#include "test_case_001.h"

int asn1scc_run_generated_testsuite(TestOutput* output)
{
    int totalErrors = 0;


    output->report_suite_begin();

    test_case_ACN_000001(output, &totalErrors);

    test_case_ACN_000002(output, &totalErrors);

    test_case_ACN_000003(output, &totalErrors);

    test_case_ACN_000004(output, &totalErrors);

    test_case_ACN_000005(output, &totalErrors);

    test_case_ACN_000006(output, &totalErrors);

    test_case_ACN_000007(output, &totalErrors);

    test_case_ACN_000008(output, &totalErrors);

    output->report_suite_end();

    if (totalErrors > 0 ) {
        output->report_tests_failed(8, totalErrors);
        return 1;
    } else {
        output->report_all_tests_passed(8);
        return 0;
    }
}
