#ifndef GENERATED_ASN1SCC_a_H
#define GENERATED_ASN1SCC_a_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint BUFFER_LENGTH_TYPE;


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2);

#define ERR_BUFFER_LENGTH_TYPE		1  /*(0..100)*/
flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode);

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal);

#define BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define BUFFER_LENGTH_TYPE_REQUIRED_BITS_FOR_ACN_ENCODING        7

#define ERR_ACN_ENCODE_BUFFER_LENGTH_TYPE		4  /**/

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_BUFFER_LENGTH_TYPE		5  /**/
flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PayloadData1 --------------------------------------------*/
typedef asn1SccSint PayloadData1_int_field;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData1_buffer;

typedef struct {
    PayloadData1_int_field int_field;
    PayloadData1_buffer buffer;

} PayloadData1;

flag PayloadData1_int_field_Equal(const PayloadData1_int_field* pVal1, const PayloadData1_int_field* pVal2);

flag PayloadData1_buffer_Equal(const PayloadData1_buffer* pVal1, const PayloadData1_buffer* pVal2);

flag PayloadData1_Equal(const PayloadData1* pVal1, const PayloadData1* pVal2);

#define ERR_PAYLOADDATA1_INT_FIELD		6  /*(-2147483648..2147483647)*/
flag PayloadData1_int_field_IsConstraintValid(const PayloadData1_int_field* pVal, int* pErrCode);

#define ERR_PAYLOADDATA1_BUFFER		11  /*(SIZE(0..100))*/
flag PayloadData1_buffer_IsConstraintValid(const PayloadData1_buffer* pVal, int* pErrCode);

#define ERR_PAYLOADDATA1		16  /**/
flag PayloadData1_IsConstraintValid(const PayloadData1* pVal, int* pErrCode);

void PayloadData1_int_field_Initialize(PayloadData1_int_field* pVal);
void PayloadData1_buffer_Initialize(PayloadData1_buffer* pVal);
void PayloadData1_Initialize(PayloadData1* pVal);

#define PayloadData1_REQUIRED_BYTES_FOR_ACN_ENCODING       104
#define PayloadData1_REQUIRED_BITS_FOR_ACN_ENCODING        832
/*-- PayloadData2 --------------------------------------------*/
typedef asn1SccSint PayloadData2_int_field;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData2_buffer;

typedef struct {
    PayloadData2_int_field int_field;
    PayloadData2_buffer buffer;

} PayloadData2;

flag PayloadData2_int_field_Equal(const PayloadData2_int_field* pVal1, const PayloadData2_int_field* pVal2);

flag PayloadData2_buffer_Equal(const PayloadData2_buffer* pVal1, const PayloadData2_buffer* pVal2);

flag PayloadData2_Equal(const PayloadData2* pVal1, const PayloadData2* pVal2);

#define ERR_PAYLOADDATA2_INT_FIELD		21  /*(-2147483648..2147483647)*/
flag PayloadData2_int_field_IsConstraintValid(const PayloadData2_int_field* pVal, int* pErrCode);

#define ERR_PAYLOADDATA2_BUFFER		26  /*(SIZE(0..100))*/
flag PayloadData2_buffer_IsConstraintValid(const PayloadData2_buffer* pVal, int* pErrCode);

#define ERR_PAYLOADDATA2		31  /**/
flag PayloadData2_IsConstraintValid(const PayloadData2* pVal, int* pErrCode);

void PayloadData2_int_field_Initialize(PayloadData2_int_field* pVal);
void PayloadData2_buffer_Initialize(PayloadData2_buffer* pVal);
void PayloadData2_Initialize(PayloadData2* pVal);

#define PayloadData2_REQUIRED_BYTES_FOR_ACN_ENCODING       104
#define PayloadData2_REQUIRED_BITS_FOR_ACN_ENCODING        832
/*-- Payload_t --------------------------------------------*/

typedef enum {
    Payload_t_NONE,
    case1_PRESENT,
    case2_PRESENT
} Payload_t_selection;

typedef union {
    PayloadData1 case1;
    PayloadData2 case2;
} Payload_t_unchecked_union;

typedef struct {
    Payload_t_selection kind;

    Payload_t_unchecked_union u;
} Payload_t;

flag Payload_t_Equal(const Payload_t* pVal1, const Payload_t* pVal2);

#define ERR_PAYLOAD_T		72  /**/
#define ERR_PAYLOAD_T_CASE1_2		51  /**/
#define ERR_PAYLOAD_T_CASE2_2		69  /**/
flag Payload_t_IsConstraintValid(const Payload_t* pVal, int* pErrCode);

void Payload_t_Initialize(Payload_t* pVal);

#define Payload_t_REQUIRED_BYTES_FOR_ACN_ENCODING       105
#define Payload_t_REQUIRED_BITS_FOR_ACN_ENCODING        833
/*-- Header --------------------------------------------*/
typedef struct {

} Header;

flag Header_Equal(const Header* pVal1, const Header* pVal2);

#define ERR_HEADER		77  /**/
flag Header_IsConstraintValid(const Header* pVal, int* pErrCode);

void Header_Initialize(Header* pVal);

#define Header_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define Header_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDU --------------------------------------------*/
typedef struct {
    Header hdr;
    Payload_t payload;

} PDU;

flag PDU_Equal(const PDU* pVal1, const PDU* pVal2);

#define ERR_PDU		139  /**/
#define ERR_PDU_HDR_2		92  /**/
#define ERR_PDU_PAYLOAD_2		136  /**/
flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode);

void PDU_Initialize(PDU* pVal);

#define PDU_REQUIRED_BYTES_FOR_ACN_ENCODING       107
#define PDU_REQUIRED_BITS_FOR_ACN_ENCODING        849

#define ERR_ACN_ENCODE_PDU		142  /**/
#define ERR_ACN_ENCODE_PDU_HDR		90  /**/
#define ERR_ACN_ENCODE_PDU_HDR_VERSION		82  /**/
#define ERR_ACN_ENCODE_UPDATE_PDU_PAYLOAD_BUFFER_LEN		86  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED		143  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH		84  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD		134  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE1		108  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE1_INT_FIELD		98  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE1_BUFFER		103  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE2		126  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE2_INT_FIELD		116  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE2_BUFFER		121  /**/

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PDU		144  /**/
#define ERR_ACN_DECODE_PDU_HDR		91  /**/
#define ERR_ACN_DECODE_PDU_HDR_VERSION		83  /**/
#define ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH		85  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD		135  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE1		109  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE1_INT_FIELD		99  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE1_BUFFER		104  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE2		127  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE2_INT_FIELD		117  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE2_BUFFER		122  /**/
flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
