/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "a.h"


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 100UL);
    *pErrCode = ret ? 0 :  ERR_BUFFER_LENGTH_TYPE;

	return ret;
}

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? BUFFER_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 100);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 100);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_BUFFER_LENGTH_TYPE;

    return ret && BUFFER_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode);
}


flag Header_Equal(const Header* pVal1, const Header* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag Header_IsConstraintValid(const Header* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void Header_Initialize(Header* pVal)
{
	(void)pVal;


}

flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? Header_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && Header_IsConstraintValid(pVal, pErrCode);
}


flag PayloadData1_int_field_Equal(const PayloadData1_int_field* pVal1, const PayloadData1_int_field* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag PayloadData1_buffer_Equal(const PayloadData1_buffer* pVal1, const PayloadData1_buffer* pVal2)
{
	return (pVal1->nCount == pVal2->nCount) && (memcmp(pVal1->arr, pVal2->arr, pVal1->nCount) ==0);

}

flag PayloadData1_Equal(const PayloadData1* pVal1, const PayloadData1* pVal2)
{
	flag ret=TRUE;

    ret = PayloadData1_int_field_Equal((&(pVal1->int_field)), (&(pVal2->int_field)));
    
    if (ret) {
        ret = PayloadData1_buffer_Equal((&(pVal1->buffer)), (&(pVal2->buffer)));
    
    }

	return ret;

}

flag PayloadData1_int_field_IsConstraintValid(const PayloadData1_int_field* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA1_INT_FIELD;

	return ret;
}

flag PayloadData1_buffer_IsConstraintValid(const PayloadData1_buffer* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 100);
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA1_BUFFER;

	return ret;
}

flag PayloadData1_IsConstraintValid(const PayloadData1* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PayloadData1_int_field_IsConstraintValid((&(pVal->int_field)), pErrCode);
    if (ret) {
        ret = PayloadData1_buffer_IsConstraintValid((&(pVal->buffer)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PayloadData1_int_field_Initialize(PayloadData1_int_field* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void PayloadData1_buffer_Initialize(PayloadData1_buffer* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 100);
	pVal->nCount = 0;

}
void PayloadData1_Initialize(PayloadData1* pVal)
{
	(void)pVal;


	/*set int_field */
	PayloadData1_int_field_Initialize((&(pVal->int_field)));
	/*set buffer */
	PayloadData1_buffer_Initialize((&(pVal->buffer)));
}

flag PayloadData1_ACN_Encode(const PayloadData1* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? PayloadData1_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode int_field */
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->int_field, -2147483648LL, 2147483647LL);
	    if (ret) {
	        /*Encode buffer */
	        BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->buffer.nCount, 0, 100);
	        ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->buffer.arr, pVal->buffer.nCount);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PayloadData1_ACN_Decode(PayloadData1* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint nCount;

	/*Decode int_field */
	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->int_field)), -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOADDATA1_INT_FIELD;
	if (ret) {
	    /*Decode buffer */
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 100);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOADDATA1_BUFFER;
	    pVal->buffer.nCount = (long)nCount;
	    ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->buffer.arr, pVal->buffer.nCount);
	}   /*COVERAGE_IGNORE*/

    return ret && PayloadData1_IsConstraintValid(pVal, pErrCode);
}


flag PayloadData2_int_field_Equal(const PayloadData2_int_field* pVal1, const PayloadData2_int_field* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag PayloadData2_buffer_Equal(const PayloadData2_buffer* pVal1, const PayloadData2_buffer* pVal2)
{
	return (pVal1->nCount == pVal2->nCount) && (memcmp(pVal1->arr, pVal2->arr, pVal1->nCount) ==0);

}

flag PayloadData2_Equal(const PayloadData2* pVal1, const PayloadData2* pVal2)
{
	flag ret=TRUE;

    ret = PayloadData2_int_field_Equal((&(pVal1->int_field)), (&(pVal2->int_field)));
    
    if (ret) {
        ret = PayloadData2_buffer_Equal((&(pVal1->buffer)), (&(pVal2->buffer)));
    
    }

	return ret;

}

flag PayloadData2_int_field_IsConstraintValid(const PayloadData2_int_field* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA2_INT_FIELD;

	return ret;
}

flag PayloadData2_buffer_IsConstraintValid(const PayloadData2_buffer* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 100);
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA2_BUFFER;

	return ret;
}

flag PayloadData2_IsConstraintValid(const PayloadData2* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PayloadData2_int_field_IsConstraintValid((&(pVal->int_field)), pErrCode);
    if (ret) {
        ret = PayloadData2_buffer_IsConstraintValid((&(pVal->buffer)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PayloadData2_int_field_Initialize(PayloadData2_int_field* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void PayloadData2_buffer_Initialize(PayloadData2_buffer* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 100);
	pVal->nCount = 0;

}
void PayloadData2_Initialize(PayloadData2* pVal)
{
	(void)pVal;


	/*set int_field */
	PayloadData2_int_field_Initialize((&(pVal->int_field)));
	/*set buffer */
	PayloadData2_buffer_Initialize((&(pVal->buffer)));
}

flag PayloadData2_ACN_Encode(const PayloadData2* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? PayloadData2_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode int_field */
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->int_field, -2147483648LL, 2147483647LL);
	    if (ret) {
	        /*Encode buffer */
	        BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->buffer.nCount, 0, 100);
	        ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->buffer.arr, pVal->buffer.nCount);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PayloadData2_ACN_Decode(PayloadData2* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint nCount;

	/*Decode int_field */
	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->int_field)), -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOADDATA2_INT_FIELD;
	if (ret) {
	    /*Decode buffer */
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 100);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOADDATA2_BUFFER;
	    pVal->buffer.nCount = (long)nCount;
	    ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->buffer.arr, pVal->buffer.nCount);
	}   /*COVERAGE_IGNORE*/

    return ret && PayloadData2_IsConstraintValid(pVal, pErrCode);
}


flag Payload_t_Equal(const Payload_t* pVal1, const Payload_t* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->kind == pVal2->kind);
    if (ret) {
    	switch(pVal1->kind)
    	{
    	case case1_PRESENT:
    		ret = PayloadData1_Equal((&(pVal1->u.case1)), (&(pVal2->u.case1)));
    		break;
    	case case2_PRESENT:
    		ret = PayloadData2_Equal((&(pVal1->u.case2)), (&(pVal2->u.case2)));
    		break;
    	default: /*COVERAGE_IGNORE*/
    		ret = FALSE;    /*COVERAGE_IGNORE*/
    	}
    } /*COVERAGE_IGNORE*/
	return ret;

}

flag Payload_t_IsConstraintValid(const Payload_t* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case case1_PRESENT : 
            ret = PayloadData1_IsConstraintValid((&(pVal->u.case1)), pErrCode);
            break;          
        case case2_PRESENT : 
            ret = PayloadData2_IsConstraintValid((&(pVal->u.case2)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_PAYLOAD_T;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

void Payload_t_Initialize(Payload_t* pVal)
{
	(void)pVal;


	pVal->kind = case1_PRESENT;
	PayloadData1_Initialize((&(pVal->u.case1)));
}

flag Payload_t_ACN_Encode(const Payload_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? Payload_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case case1_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	    	ret = PayloadData1_ACN_Encode((&(pVal->u.case1)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case case2_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	    	ret = PayloadData2_ACN_Encode((&(pVal->u.case2)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_ENCODE_PAYLOAD_T;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    } /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Payload_t_ACN_Decode(Payload_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint MyModule_Payload_t_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &MyModule_Payload_t_index_tmp, 0, 1);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOAD_T;
	if (ret) {
	    switch(MyModule_Payload_t_index_tmp)
	    {
	    case 0:
	    	pVal->kind = case1_PRESENT;
	    	ret = PayloadData1_ACN_Decode((&(pVal->u.case1)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = case2_PRESENT;
	    	ret = PayloadData2_ACN_Decode((&(pVal->u.case2)), pBitStrm, pErrCode);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_PAYLOAD_T;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && Payload_t_IsConstraintValid(pVal, pErrCode);
}


flag PDU_Equal(const PDU* pVal1, const PDU* pVal2)
{
	flag ret=TRUE;

    ret = Header_Equal((&(pVal1->hdr)), (&(pVal2->hdr)));
    
    if (ret) {
        ret = Payload_t_Equal((&(pVal1->payload)), (&(pVal2->payload)));
    
    }

	return ret;

}

flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Header_IsConstraintValid((&(pVal->hdr)), pErrCode);
    if (ret) {
        ret = Payload_t_IsConstraintValid((&(pVal->payload)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PDU_Initialize(PDU* pVal)
{
	(void)pVal;


	/*set hdr */
	Header_Initialize((&(pVal->hdr)));
	/*set payload */
	Payload_t_Initialize((&(pVal->payload)));
}

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint PDU_hdr_buffers_length;
	flag PDU_hdr_buffers_length_is_initialized=FALSE;
    *pErrCode = 0;
	ret = bCheckConstraints ? PDU_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode hdr */
	    /*Encode PDU_hdr_version */
	    {
	    	static byte tmp[] = {0x01};
	    	BitStream_AppendBits(pBitStrm, tmp, 8);
	    }
	    if (ret) {
	        {
	            asn1SccUint PDU_hdr_buffers_length00;
	            flag PDU_hdr_buffers_length00_is_initialized=FALSE;
	            asn1SccUint PDU_hdr_buffers_length01;
	            flag PDU_hdr_buffers_length01_is_initialized=FALSE;

	            if (pVal->payload.kind == case2_PRESENT) {
	                PDU_hdr_buffers_length00_is_initialized = TRUE;
	                PDU_hdr_buffers_length00 = pVal->payload.u.case2.buffer.nCount;
	            }
	            if (pVal->payload.kind == case1_PRESENT) {
	                PDU_hdr_buffers_length01_is_initialized = TRUE;
	                PDU_hdr_buffers_length01 = pVal->payload.u.case1.buffer.nCount;
	            }

	            if (ret) {

	                *pErrCode = ERR_ACN_ENCODE_UPDATE_PDU_HDR_BUFFERS_LENGTH;
	                if (PDU_hdr_buffers_length00_is_initialized) { /*COVERAGE_IGNORE*/
	                    PDU_hdr_buffers_length = PDU_hdr_buffers_length00; /*COVERAGE_IGNORE*/
	                } /*COVERAGE_IGNORE*/ else if (PDU_hdr_buffers_length01_is_initialized) { /*COVERAGE_IGNORE*/
	                    PDU_hdr_buffers_length = PDU_hdr_buffers_length01; /*COVERAGE_IGNORE*/
	                } /*COVERAGE_IGNORE*/ else {
	                    ret = FALSE; /*COVERAGE_IGNORE*/
	                }
	                if (ret) {
	                    ret = (((PDU_hdr_buffers_length00_is_initialized && PDU_hdr_buffers_length == PDU_hdr_buffers_length00) || !PDU_hdr_buffers_length00_is_initialized) && ((PDU_hdr_buffers_length01_is_initialized && PDU_hdr_buffers_length == PDU_hdr_buffers_length01) || !PDU_hdr_buffers_length01_is_initialized));
	                    PDU_hdr_buffers_length_is_initialized = TRUE;
	                }
	            }
	        }
	        if (ret) {
	            /*Encode PDU_hdr_buffers_length */
	            if (PDU_hdr_buffers_length_is_initialized) {
	                ret = TRUE;
	                Acn_Enc_Int_PositiveInteger_ConstSize_8(pBitStrm, PDU_hdr_buffers_length);
	            } else {
	                *pErrCode = ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED;         /*COVERAGE_IGNORE*/
	                ret = FALSE;                    /*COVERAGE_IGNORE*/
	            }
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	    if (ret) {
	        /*Encode payload */
	        switch(pVal->payload.kind)
	        {
	        case case1_PRESENT:
	        	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	        	/*Encode int_field */
	        	Acn_Enc_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, pVal->payload.u.case1.int_field);
	        	if (ret) {
	        	    /*Encode buffer */
	        	    ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->payload.u.case1.buffer.arr, pVal->payload.u.case1.buffer.nCount);
	        	}   /*COVERAGE_IGNORE*/
	        	break;
	        case case2_PRESENT:
	        	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	        	/*Encode int_field */
	        	Acn_Enc_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, pVal->payload.u.case2.int_field);
	        	if (ret) {
	        	    /*Encode buffer */
	        	    ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->payload.u.case2.buffer.arr, pVal->payload.u.case2.buffer.nCount);
	        	}   /*COVERAGE_IGNORE*/
	        	break;
	        default: /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_PDU_PAYLOAD;         /*COVERAGE_IGNORE*/
	            ret = FALSE;                    /*COVERAGE_IGNORE*/
	        } /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint PDU_hdr_buffers_length;
	asn1SccSint MyModule_PDU_payload_index_tmp;

	/*Decode hdr */
	/*Decode PDU_hdr_version */
	{
		static byte tmp[] = {0x01};
	    flag bDecodingPatternMatches;
		ret = BitStream_ReadBitPattern(pBitStrm, tmp, 8, &bDecodingPatternMatches);
	    ret = ret && bDecodingPatternMatches;
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_VERSION;
	}
	
	if (ret) {
	    /*Decode PDU_hdr_buffers_length */
	    ret = Acn_Dec_Int_PositiveInteger_ConstSize_8(pBitStrm, (&(PDU_hdr_buffers_length)));
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH;
	}   /*COVERAGE_IGNORE*/
	if (ret) {
	    /*Decode payload */
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &MyModule_PDU_payload_index_tmp, 0, 1);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD;
	    if (ret) {
	        switch(MyModule_PDU_payload_index_tmp)
	        {
	        case 0:
	        	pVal->payload.kind = case1_PRESENT;
	        	/*Decode int_field */
	        	ret = Acn_Dec_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, (&(pVal->payload.u.case1.int_field)));
	        	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_CASE1_INT_FIELD;
	        	if (ret) {
	        	    /*Decode buffer */
	        	    ret = ((PDU_hdr_buffers_length<=100));
	        	    if (ret) {
	        	        pVal->payload.u.case1.buffer.nCount = (int)PDU_hdr_buffers_length;
	        	        ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->payload.u.case1.buffer.arr, pVal->payload.u.case1.buffer.nCount);
	        	    	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_CASE1_BUFFER;
	        	    }
	        	}   /*COVERAGE_IGNORE*/
	        	break;
	        case 1:
	        	pVal->payload.kind = case2_PRESENT;
	        	/*Decode int_field */
	        	ret = Acn_Dec_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, (&(pVal->payload.u.case2.int_field)));
	        	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_CASE2_INT_FIELD;
	        	if (ret) {
	        	    /*Decode buffer */
	        	    ret = ((PDU_hdr_buffers_length<=100));
	        	    if (ret) {
	        	        pVal->payload.u.case2.buffer.nCount = (int)PDU_hdr_buffers_length;
	        	        ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->payload.u.case2.buffer.arr, pVal->payload.u.case2.buffer.nCount);
	        	    	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_CASE2_BUFFER;
	        	    }
	        	}   /*COVERAGE_IGNORE*/
	        	break;
	        default: /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_DECODE_PDU_PAYLOAD;     /*COVERAGE_IGNORE*/
	            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && PDU_IsConstraintValid(pVal, pErrCode);
}


