#ifndef GENERATED_ASN1SCC_a_H
#define GENERATED_ASN1SCC_a_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint BUFFER_LENGTH_TYPE;


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2);

#define ERR_BUFFER_LENGTH_TYPE		1  /*(0..100)*/
flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode);

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal);

#define BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define BUFFER_LENGTH_TYPE_REQUIRED_BITS_FOR_ACN_ENCODING        7

#define ERR_ACN_ENCODE_BUFFER_LENGTH_TYPE		4  /**/

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_BUFFER_LENGTH_TYPE		5  /**/
flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- Header --------------------------------------------*/
typedef struct {

} Header;

flag Header_Equal(const Header* pVal1, const Header* pVal2);

#define ERR_HEADER		6  /**/
flag Header_IsConstraintValid(const Header* pVal, int* pErrCode);

void Header_Initialize(Header* pVal);

#define Header_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define Header_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PayloadData1 --------------------------------------------*/
typedef asn1SccSint PayloadData1_int_field;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData1_buffer;

typedef struct {
    PayloadData1_int_field int_field;
    PayloadData1_buffer buffer;

} PayloadData1;

flag PayloadData1_int_field_Equal(const PayloadData1_int_field* pVal1, const PayloadData1_int_field* pVal2);

flag PayloadData1_buffer_Equal(const PayloadData1_buffer* pVal1, const PayloadData1_buffer* pVal2);

flag PayloadData1_Equal(const PayloadData1* pVal1, const PayloadData1* pVal2);

#define ERR_PAYLOADDATA1_INT_FIELD		11  /*(-2147483648..2147483647)*/
flag PayloadData1_int_field_IsConstraintValid(const PayloadData1_int_field* pVal, int* pErrCode);

#define ERR_PAYLOADDATA1_BUFFER		16  /*(SIZE(0..100))*/
flag PayloadData1_buffer_IsConstraintValid(const PayloadData1_buffer* pVal, int* pErrCode);

#define ERR_PAYLOADDATA1		21  /**/
flag PayloadData1_IsConstraintValid(const PayloadData1* pVal, int* pErrCode);

void PayloadData1_int_field_Initialize(PayloadData1_int_field* pVal);
void PayloadData1_buffer_Initialize(PayloadData1_buffer* pVal);
void PayloadData1_Initialize(PayloadData1* pVal);

#define PayloadData1_REQUIRED_BYTES_FOR_ACN_ENCODING       105
#define PayloadData1_REQUIRED_BITS_FOR_ACN_ENCODING        839

#define ERR_ACN_ENCODE_PAYLOADDATA1		24  /**/
#define ERR_ACN_ENCODE_PAYLOADDATA1_INT_FIELD		14  /**/
#define ERR_ACN_ENCODE_PAYLOADDATA1_BUFFER		19  /**/

flag PayloadData1_ACN_Encode(const PayloadData1* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PAYLOADDATA1		25  /**/
#define ERR_ACN_DECODE_PAYLOADDATA1_INT_FIELD		15  /**/
#define ERR_ACN_DECODE_PAYLOADDATA1_BUFFER		20  /**/
flag PayloadData1_ACN_Decode(PayloadData1* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PayloadData2 --------------------------------------------*/
typedef asn1SccSint PayloadData2_int_field;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData2_buffer;

typedef struct {
    PayloadData2_int_field int_field;
    PayloadData2_buffer buffer;

} PayloadData2;

flag PayloadData2_int_field_Equal(const PayloadData2_int_field* pVal1, const PayloadData2_int_field* pVal2);

flag PayloadData2_buffer_Equal(const PayloadData2_buffer* pVal1, const PayloadData2_buffer* pVal2);

flag PayloadData2_Equal(const PayloadData2* pVal1, const PayloadData2* pVal2);

#define ERR_PAYLOADDATA2_INT_FIELD		26  /*(-2147483648..2147483647)*/
flag PayloadData2_int_field_IsConstraintValid(const PayloadData2_int_field* pVal, int* pErrCode);

#define ERR_PAYLOADDATA2_BUFFER		31  /*(SIZE(0..100))*/
flag PayloadData2_buffer_IsConstraintValid(const PayloadData2_buffer* pVal, int* pErrCode);

#define ERR_PAYLOADDATA2		36  /**/
flag PayloadData2_IsConstraintValid(const PayloadData2* pVal, int* pErrCode);

void PayloadData2_int_field_Initialize(PayloadData2_int_field* pVal);
void PayloadData2_buffer_Initialize(PayloadData2_buffer* pVal);
void PayloadData2_Initialize(PayloadData2* pVal);

#define PayloadData2_REQUIRED_BYTES_FOR_ACN_ENCODING       105
#define PayloadData2_REQUIRED_BITS_FOR_ACN_ENCODING        839

#define ERR_ACN_ENCODE_PAYLOADDATA2		39  /**/
#define ERR_ACN_ENCODE_PAYLOADDATA2_INT_FIELD		29  /**/
#define ERR_ACN_ENCODE_PAYLOADDATA2_BUFFER		34  /**/

flag PayloadData2_ACN_Encode(const PayloadData2* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PAYLOADDATA2		40  /**/
#define ERR_ACN_DECODE_PAYLOADDATA2_INT_FIELD		30  /**/
#define ERR_ACN_DECODE_PAYLOADDATA2_BUFFER		35  /**/
flag PayloadData2_ACN_Decode(PayloadData2* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- Payload_t --------------------------------------------*/

typedef enum {
    Payload_t_NONE,
    case1_PRESENT,
    case2_PRESENT
} Payload_t_selection;

typedef union {
    PayloadData1 case1;
    PayloadData2 case2;
} Payload_t_unchecked_union;

typedef struct {
    Payload_t_selection kind;

    Payload_t_unchecked_union u;
} Payload_t;

flag Payload_t_Equal(const Payload_t* pVal1, const Payload_t* pVal2);

#define ERR_PAYLOAD_T		51  /**/
#define ERR_PAYLOAD_T_CASE1		41  /**/
#define ERR_PAYLOAD_T_CASE2		46  /**/
flag Payload_t_IsConstraintValid(const Payload_t* pVal, int* pErrCode);

void Payload_t_Initialize(Payload_t* pVal);

#define Payload_t_REQUIRED_BYTES_FOR_ACN_ENCODING       105
#define Payload_t_REQUIRED_BITS_FOR_ACN_ENCODING        840

#define ERR_ACN_ENCODE_PAYLOAD_T		54  /**/
#define ERR_ACN_ENCODE_PAYLOAD_T_CASE1		44  /**/
#define ERR_ACN_ENCODE_PAYLOAD_T_CASE2		49  /**/

flag Payload_t_ACN_Encode(const Payload_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PAYLOAD_T		55  /**/
#define ERR_ACN_DECODE_PAYLOAD_T_CASE1		45  /**/
#define ERR_ACN_DECODE_PAYLOAD_T_CASE2		50  /**/
flag Payload_t_ACN_Decode(Payload_t* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDU --------------------------------------------*/
typedef struct {
    Header hdr;
    Payload_t payload;

} PDU;

flag PDU_Equal(const PDU* pVal1, const PDU* pVal2);

#define ERR_PDU		113  /**/
#define ERR_PDU_HDR_2		66  /**/
#define ERR_PDU_PAYLOAD_2		110  /**/
flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode);

void PDU_Initialize(PDU* pVal);

#define PDU_REQUIRED_BYTES_FOR_ACN_ENCODING       107
#define PDU_REQUIRED_BITS_FOR_ACN_ENCODING        849

#define ERR_ACN_ENCODE_PDU		116  /**/
#define ERR_ACN_ENCODE_PDU_HDR		64  /**/
#define ERR_ACN_ENCODE_PDU_HDR_VERSION		56  /**/
#define ERR_ACN_ENCODE_UPDATE_PDU_HDR_BUFFERS_LENGTH		60  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED		117  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH		58  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD		108  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE1		82  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE1_INT_FIELD		72  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE1_BUFFER		77  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE2		100  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE2_INT_FIELD		90  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_CASE2_BUFFER		95  /**/

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PDU		118  /**/
#define ERR_ACN_DECODE_PDU_HDR		65  /**/
#define ERR_ACN_DECODE_PDU_HDR_VERSION		57  /**/
#define ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH		59  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD		109  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE1		83  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE1_INT_FIELD		73  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE1_BUFFER		78  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE2		101  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE2_INT_FIELD		91  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_CASE2_BUFFER		96  /**/
flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
