#ifndef GENERATED_ASN1SCC_a_auto_tcs_h
#define GENERATED_ASN1SCC_a_auto_tcs_h
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "a.h"

#ifdef  __cplusplus
extern "C" {
#endif


flag BUFFER_LENGTH_TYPE_ACN_enc_dec(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode, const char* filename);

flag PayloadData1_ACN_enc_dec(const PayloadData1* pVal, int* pErrCode, const char* filename);

flag PayloadData2_ACN_enc_dec(const PayloadData2* pVal, int* pErrCode, const char* filename);

flag Payload_t_ACN_enc_dec(const Payload_t* pVal, int* pErrCode, const char* filename);

flag PDU_ACN_enc_dec(const PDU* pVal, int* pErrCode, const char* filename);



#ifdef  __cplusplus
}
#endif

#endif
