/*  Code automatically generated by asn1scc tool (stg macro : printTestCaseFileBody) */

#include "test_case_001.h"

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>

#ifndef _MSC_VER
#include <sys/time.h>

#endif // _MSC_VER

#include "asn1crt.h"

#include "a_auto_tcs.h"

void test_case_ACN_000001(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000001");
    {
        // dummy statement used for calling init functions
BUFFER_LENGTH_TYPE tmp0;
        BUFFER_LENGTH_TYPE_Initialize((&(tmp0)));
    }

BUFFER_LENGTH_TYPE tc_data; 
    tc_data = 0UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000001");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("BUFFER_LENGTH_TYPE/test_case_ACN_000001", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000001");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000001 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000001'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000002(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000002");
    {
        // dummy statement used for calling init functions
BUFFER_LENGTH_TYPE tmp0;
        BUFFER_LENGTH_TYPE_Initialize((&(tmp0)));
    }

BUFFER_LENGTH_TYPE tc_data; 
    tc_data = 100UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000002");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("BUFFER_LENGTH_TYPE/test_case_ACN_000002", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000002");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000002 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000002'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000003(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000003");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set payload */
    /*set case1*/
    tc_data.payload.kind = case1_PRESENT;
    /*set int_field */
    tc_data.payload.u.case1.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.payload.u.case1.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.payload.u.case1.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000003");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000003", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000003");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000003 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000003'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000004(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000004");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set payload */
    /*set case1*/
    tc_data.payload.kind = case1_PRESENT;
    /*set int_field */
    tc_data.payload.u.case1.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.payload.u.case1.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.payload.u.case1.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000004");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000004", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000004");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000004 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000004'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000005(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000005");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set payload */
    /*set case2*/
    tc_data.payload.kind = case2_PRESENT;
    /*set int_field */
    tc_data.payload.u.case2.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.payload.u.case2.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.payload.u.case2.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000005");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000005", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000005");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000005 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000005'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000006(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000006");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set payload */
    /*set case2*/
    tc_data.payload.kind = case2_PRESENT;
    /*set int_field */
    tc_data.payload.u.case2.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.payload.u.case2.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.payload.u.case2.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000006");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000006", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000006");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000006 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000006'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000007(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000007");
    {
        // dummy statement used for calling init functions
        static Payload_t tmp0;
        Payload_t_Initialize((&(tmp0)));
    }

    static Payload_t tc_data; 
    /*set case1*/
    tc_data.kind = case1_PRESENT;
    /*set int_field */
    tc_data.u.case1.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.u.case1.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.u.case1.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000007");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("Payload_t/test_case_ACN_000007", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000007");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000007 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000007' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000007' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000007' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000007'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000008(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000008");
    {
        // dummy statement used for calling init functions
        static Payload_t tmp0;
        Payload_t_Initialize((&(tmp0)));
    }

    static Payload_t tc_data; 
    /*set case1*/
    tc_data.kind = case1_PRESENT;
    /*set int_field */
    tc_data.u.case1.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.u.case1.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.u.case1.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000008");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("Payload_t/test_case_ACN_000008", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000008");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000008 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000008' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000008' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000008' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000008'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000009(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000009");
    {
        // dummy statement used for calling init functions
        static Payload_t tmp0;
        Payload_t_Initialize((&(tmp0)));
    }

    static Payload_t tc_data; 
    /*set case2*/
    tc_data.kind = case2_PRESENT;
    /*set int_field */
    tc_data.u.case2.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.u.case2.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.u.case2.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000009");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("Payload_t/test_case_ACN_000009", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000009");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000009 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000009' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000009' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000009' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000009'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000010(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000010");
    {
        // dummy statement used for calling init functions
        static Payload_t tmp0;
        Payload_t_Initialize((&(tmp0)));
    }

    static Payload_t tc_data; 
    /*set case2*/
    tc_data.kind = case2_PRESENT;
    /*set int_field */
    tc_data.u.case2.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.u.case2.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.u.case2.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000010");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("Payload_t/test_case_ACN_000010", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = Payload_t_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000010");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000010 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000010' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000010' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000010' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000010'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000011(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000011");
    {
        // dummy statement used for calling init functions
        static PayloadData1 tmp0;
        PayloadData1_int_field_Initialize((&(tmp0.int_field)));
        PayloadData1_buffer_Initialize((&(tmp0.buffer)));
        PayloadData1_Initialize((&(tmp0)));
    }

    static PayloadData1 tc_data; 
    /*set int_field */
    tc_data.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PayloadData1_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000011");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PayloadData1/test_case_ACN_000011", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PayloadData1_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000011");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000011 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000011' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000011' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000011' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000011'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000012(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000012");
    {
        // dummy statement used for calling init functions
        static PayloadData1 tmp0;
        PayloadData1_int_field_Initialize((&(tmp0.int_field)));
        PayloadData1_buffer_Initialize((&(tmp0.buffer)));
        PayloadData1_Initialize((&(tmp0)));
    }

    static PayloadData1 tc_data; 
    /*set int_field */
    tc_data.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PayloadData1_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000012");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PayloadData1/test_case_ACN_000012", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PayloadData1_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000012");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000012 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000012' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000012' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000012' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000012'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000013(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000013");
    {
        // dummy statement used for calling init functions
        static PayloadData2 tmp0;
        PayloadData2_int_field_Initialize((&(tmp0.int_field)));
        PayloadData2_buffer_Initialize((&(tmp0.buffer)));
        PayloadData2_Initialize((&(tmp0)));
    }

    static PayloadData2 tc_data; 
    /*set int_field */
    tc_data.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PayloadData2_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000013");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PayloadData2/test_case_ACN_000013", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PayloadData2_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000013");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000013 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000013' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000013' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000013' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000013'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000014(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000014");
    {
        // dummy statement used for calling init functions
        static PayloadData2 tmp0;
        PayloadData2_int_field_Initialize((&(tmp0.int_field)));
        PayloadData2_buffer_Initialize((&(tmp0.buffer)));
        PayloadData2_Initialize((&(tmp0)));
    }

    static PayloadData2 tc_data; 
    /*set int_field */
    tc_data.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PayloadData2_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000014");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PayloadData2/test_case_ACN_000014", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PayloadData2_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000014");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000014 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000014' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000014' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000014' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000014'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}
