/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "a.h"


flag PDU_LENGTH_TYPE_Equal(const PDU_LENGTH_TYPE* pVal1, const PDU_LENGTH_TYPE* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag PDU_LENGTH_TYPE_IsConstraintValid(const PDU_LENGTH_TYPE* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 65535UL);
    *pErrCode = ret ? 0 :  ERR_PDU_LENGTH_TYPE;

	return ret;
}

void PDU_LENGTH_TYPE_Initialize(PDU_LENGTH_TYPE* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag PDU_LENGTH_TYPE_ACN_Encode(const PDU_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? PDU_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 65535);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDU_LENGTH_TYPE_ACN_Decode(PDU_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 65535);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_LENGTH_TYPE;

    return ret && PDU_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode);
}


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 100UL);
    *pErrCode = ret ? 0 :  ERR_BUFFER_LENGTH_TYPE;

	return ret;
}

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? BUFFER_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 100);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 100);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_BUFFER_LENGTH_TYPE;

    return ret && BUFFER_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode);
}


flag PayloadData_int_field_Equal(const PayloadData_int_field* pVal1, const PayloadData_int_field* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag PayloadData_buffer1_Equal(const PayloadData_buffer1* pVal1, const PayloadData_buffer1* pVal2)
{
	return (pVal1->nCount == pVal2->nCount) && (memcmp(pVal1->arr, pVal2->arr, pVal1->nCount) ==0);

}

flag PayloadData_buffer2_Equal(const PayloadData_buffer2* pVal1, const PayloadData_buffer2* pVal2)
{
	return (pVal1->nCount == pVal2->nCount) && (memcmp(pVal1->arr, pVal2->arr, pVal1->nCount) ==0);

}

flag PayloadData_Equal(const PayloadData* pVal1, const PayloadData* pVal2)
{
	flag ret=TRUE;

    ret = PayloadData_int_field_Equal((&(pVal1->int_field)), (&(pVal2->int_field)));
    
    if (ret) {
        ret = PayloadData_buffer1_Equal((&(pVal1->buffer1)), (&(pVal2->buffer1)));
        
        if (ret) {
            ret = PayloadData_buffer2_Equal((&(pVal1->buffer2)), (&(pVal2->buffer2)));
        
        }
    
    }

	return ret;

}

flag PayloadData_int_field_IsConstraintValid(const PayloadData_int_field* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA_INT_FIELD;

	return ret;
}

flag PayloadData_buffer1_IsConstraintValid(const PayloadData_buffer1* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 100);
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA_BUFFER1;

	return ret;
}

flag PayloadData_buffer2_IsConstraintValid(const PayloadData_buffer2* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 100);
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA_BUFFER2;

	return ret;
}

flag PayloadData_IsConstraintValid(const PayloadData* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PayloadData_int_field_IsConstraintValid((&(pVal->int_field)), pErrCode);
    if (ret) {
        ret = PayloadData_buffer1_IsConstraintValid((&(pVal->buffer1)), pErrCode);
        if (ret) {
            ret = PayloadData_buffer2_IsConstraintValid((&(pVal->buffer2)), pErrCode);
        }   /*COVERAGE_IGNORE*/
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PayloadData_int_field_Initialize(PayloadData_int_field* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void PayloadData_buffer1_Initialize(PayloadData_buffer1* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 100);
	pVal->nCount = 0;

}
void PayloadData_buffer2_Initialize(PayloadData_buffer2* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 100);
	pVal->nCount = 0;

}
void PayloadData_Initialize(PayloadData* pVal)
{
	(void)pVal;


	/*set int_field */
	PayloadData_int_field_Initialize((&(pVal->int_field)));
	/*set buffer1 */
	PayloadData_buffer1_Initialize((&(pVal->buffer1)));
	/*set buffer2 */
	PayloadData_buffer2_Initialize((&(pVal->buffer2)));
}


flag Header_Equal(const Header* pVal1, const Header* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag Header_IsConstraintValid(const Header* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void Header_Initialize(Header* pVal)
{
	(void)pVal;


}

flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? Header_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && Header_IsConstraintValid(pVal, pErrCode);
}


flag PDU_Equal(const PDU* pVal1, const PDU* pVal2)
{
	flag ret=TRUE;

    ret = Header_Equal((&(pVal1->hdr)), (&(pVal2->hdr)));
    
    if (ret) {
        ret = PayloadData_Equal((&(pVal1->payload)), (&(pVal2->payload)));
    
    }

	return ret;

}

flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Header_IsConstraintValid((&(pVal->hdr)), pErrCode);
    if (ret) {
        ret = PayloadData_IsConstraintValid((&(pVal->payload)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PDU_Initialize(PDU* pVal)
{
	(void)pVal;


	/*set hdr */
	Header_Initialize((&(pVal->hdr)));
	/*set payload */
	PayloadData_Initialize((&(pVal->payload)));
}

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint PDU_hdr_pdu_length;
	flag PDU_hdr_pdu_length_is_initialized=FALSE;
	asn1SccUint PDU_hdr_buffers_length;
	flag PDU_hdr_buffers_length_is_initialized=FALSE;
	static byte arr[PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING];
	BitStream bitStrm;
    *pErrCode = 0;
	ret = bCheckConstraints ? PDU_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode hdr */
	    /*Encode PDU_hdr_version */
	    {
	    	static byte tmp[] = {0x01};
	    	BitStream_AppendBits(pBitStrm, tmp, 8);
	    }
	    if (ret) {
	        {
	            /*first encode containing type to a temporary bitstream. That's the only way to learn in advance the size of the encoding octet string*/
	            BitStream_Init(&bitStrm, arr, sizeof(arr));
	            BitStream* pBitStrm_save = pBitStrm;
	            pBitStrm = &bitStrm;
	            /*Encode int_field */
	            Acn_Enc_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, pVal->payload.int_field);
	            if (ret) {
	                /*Encode buffer1 */
	                ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->payload.buffer1.arr, pVal->payload.buffer1.nCount);
	                if (ret) {
	                    /*Encode buffer2 */
	                    ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->payload.buffer2.arr, pVal->payload.buffer2.nCount);
	                }   /*COVERAGE_IGNORE*/
	            }   /*COVERAGE_IGNORE*/
	            pBitStrm = pBitStrm_save;
	        }
	        if (ret) {
	        	PDU_hdr_pdu_length = bitStrm.currentBit == 0 ? bitStrm.currentByte : (bitStrm.currentByte + 1);
	        	PDU_hdr_pdu_length_is_initialized = TRUE;
	        }
	        
	        if (ret) {
	            /*Encode PDU_hdr_pdu_length */
	            if (PDU_hdr_pdu_length_is_initialized) {
	                ret = TRUE;
	                Acn_Enc_Int_PositiveInteger_ConstSize_big_endian_16(pBitStrm, PDU_hdr_pdu_length);
	            } else {
	                *pErrCode = ERR_ACN_ENCODE_PDU_HDR_PDU_LENGTH_UNINITIALIZED;         /*COVERAGE_IGNORE*/
	                ret = FALSE;                    /*COVERAGE_IGNORE*/
	            }
	        }   /*COVERAGE_IGNORE*/
	        if (ret) {
	            {
	                asn1SccUint PDU_payload_buffer_len00;
	                flag PDU_payload_buffer_len00_is_initialized=FALSE;
	                asn1SccUint PDU_payload_buffer_len01;
	                flag PDU_payload_buffer_len01_is_initialized=FALSE;

	                PDU_payload_buffer_len00_is_initialized = TRUE;
	                PDU_payload_buffer_len00 = pVal->payload.buffer2.nCount;
	                PDU_payload_buffer_len01_is_initialized = TRUE;
	                PDU_payload_buffer_len01 = pVal->payload.buffer1.nCount;

	                if (ret) {

	                    *pErrCode = ERR_ACN_ENCODE_UPDATE_PDU_PAYLOAD_BUFFER_LEN;
	                    if (PDU_payload_buffer_len00_is_initialized) { /*COVERAGE_IGNORE*/
	                        PDU_hdr_buffers_length = PDU_payload_buffer_len00; /*COVERAGE_IGNORE*/
	                    } /*COVERAGE_IGNORE*/ else if (PDU_payload_buffer_len01_is_initialized) { /*COVERAGE_IGNORE*/
	                        PDU_hdr_buffers_length = PDU_payload_buffer_len01; /*COVERAGE_IGNORE*/
	                    } /*COVERAGE_IGNORE*/ else {
	                        ret = FALSE; /*COVERAGE_IGNORE*/
	                    }
	                    if (ret) {
	                        ret = (((PDU_payload_buffer_len00_is_initialized && PDU_hdr_buffers_length == PDU_payload_buffer_len00) || !PDU_payload_buffer_len00_is_initialized) && ((PDU_payload_buffer_len01_is_initialized && PDU_hdr_buffers_length == PDU_payload_buffer_len01) || !PDU_payload_buffer_len01_is_initialized));
	                        PDU_hdr_buffers_length_is_initialized = TRUE;
	                    }
	                }
	            }
	            if (ret) {
	                /*Encode PDU_hdr_buffers_length */
	                if (PDU_hdr_buffers_length_is_initialized) {
	                    ret = TRUE;
	                    Acn_Enc_Int_PositiveInteger_ConstSize_8(pBitStrm, PDU_hdr_buffers_length);
	                } else {
	                    *pErrCode = ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED;         /*COVERAGE_IGNORE*/
	                    ret = FALSE;                    /*COVERAGE_IGNORE*/
	                }
	            }   /*COVERAGE_IGNORE*/
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	    if (ret) {
	        /*Encode payload */
	        ret = BitStream_EncodeOctetString_no_length(pBitStrm, arr, (int)PDU_hdr_pdu_length);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint PDU_hdr_pdu_length;
	asn1SccUint PDU_hdr_buffers_length;

	/*Decode hdr */
	/*Decode PDU_hdr_version */
	{
		static byte tmp[] = {0x01};
	    flag bDecodingPatternMatches;
		ret = BitStream_ReadBitPattern(pBitStrm, tmp, 8, &bDecodingPatternMatches);
	    ret = ret && bDecodingPatternMatches;
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_VERSION;
	}
	
	if (ret) {
	    /*Decode PDU_hdr_pdu_length */
	    ret = Acn_Dec_Int_PositiveInteger_ConstSize_big_endian_16(pBitStrm, (&(PDU_hdr_pdu_length)));
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_PDU_LENGTH;
	    if (ret) {
	        /*Decode PDU_hdr_buffers_length */
	        ret = Acn_Dec_Int_PositiveInteger_ConstSize_8(pBitStrm, (&(PDU_hdr_buffers_length)));
	        *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH;
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/
	if (ret) {
	    /*Decode payload */
	    /*open new scope to declare some variables*/
	    {
	    	
	    	static byte arr[PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING];
	        BitStream* pBitStrm_save = pBitStrm;
	    	BitStream bitStrm;
	    	BitStream_Init(&bitStrm, arr, sizeof(arr));
	    	ret = (int)PDU_hdr_pdu_length <= PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING;
	    	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_2;
	    	if (ret) {
	    		/*decode to the temporary bitstream buffer */
	    		ret = BitStream_DecodeOctetString_no_length(pBitStrm, arr, (int)PDU_hdr_pdu_length);
	    		*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_2;
	    		if (ret) {
	                pBitStrm = &bitStrm;
	                /*Decode int_field */
	                ret = Acn_Dec_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, (&(pVal->payload.int_field)));
	                *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_INT_FIELD;
	                if (ret) {
	                    /*Decode buffer1 */
	                    ret = ((PDU_hdr_buffers_length<=100));
	                    if (ret) {
	                        pVal->payload.buffer1.nCount = (int)PDU_hdr_buffers_length;
	                        ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->payload.buffer1.arr, pVal->payload.buffer1.nCount);
	                    	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_BUFFER1;
	                    }
	                    if (ret) {
	                        /*Decode buffer2 */
	                        ret = ((PDU_hdr_buffers_length<=100));
	                        if (ret) {
	                            pVal->payload.buffer2.nCount = (int)PDU_hdr_buffers_length;
	                            ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->payload.buffer2.arr, pVal->payload.buffer2.nCount);
	                        	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_BUFFER2;
	                        }
	                    }   /*COVERAGE_IGNORE*/
	                }   /*COVERAGE_IGNORE*/
	    			//ret = PayloadData_ACN_Decode((&(pVal->payload)), &bitStrm, pErrCode);
	                pBitStrm = pBitStrm_save;
	    		}
	    	}
	    }
	}   /*COVERAGE_IGNORE*/

    return ret && PDU_IsConstraintValid(pVal, pErrCode);
}


