#ifndef GENERATED_ASN1SCC_a_H
#define GENERATED_ASN1SCC_a_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"


#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint PDU_LENGTH_TYPE;


flag PDU_LENGTH_TYPE_Equal(const PDU_LENGTH_TYPE* pVal1, const PDU_LENGTH_TYPE* pVal2);

#define ERR_PDU_LENGTH_TYPE		1  /*(0..65535)*/
flag PDU_LENGTH_TYPE_IsConstraintValid(const PDU_LENGTH_TYPE* pVal, int* pErrCode);

void PDU_LENGTH_TYPE_Initialize(PDU_LENGTH_TYPE* pVal);

#define PDU_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING       2
#define PDU_LENGTH_TYPE_REQUIRED_BITS_FOR_ACN_ENCODING        16

#define ERR_ACN_ENCODE_PDU_LENGTH_TYPE		4  /**/

flag PDU_LENGTH_TYPE_ACN_Encode(const PDU_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PDU_LENGTH_TYPE		5  /**/
flag PDU_LENGTH_TYPE_ACN_Decode(PDU_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode);
typedef asn1SccUint BUFFER_LENGTH_TYPE;


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2);

#define ERR_BUFFER_LENGTH_TYPE		6  /*(0..100)*/
flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode);

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal);

#define BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define BUFFER_LENGTH_TYPE_REQUIRED_BITS_FOR_ACN_ENCODING        7

#define ERR_ACN_ENCODE_BUFFER_LENGTH_TYPE		9  /**/

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_BUFFER_LENGTH_TYPE		10  /**/
flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PayloadData --------------------------------------------*/
typedef asn1SccSint PayloadData_int_field;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData_buffer1;

typedef struct {
    int nCount;
    byte arr[100];
} PayloadData_buffer2;

typedef struct {
    PayloadData_int_field int_field;
    PayloadData_buffer1 buffer1;
    PayloadData_buffer2 buffer2;

} PayloadData;

flag PayloadData_int_field_Equal(const PayloadData_int_field* pVal1, const PayloadData_int_field* pVal2);

flag PayloadData_buffer1_Equal(const PayloadData_buffer1* pVal1, const PayloadData_buffer1* pVal2);

flag PayloadData_buffer2_Equal(const PayloadData_buffer2* pVal1, const PayloadData_buffer2* pVal2);

flag PayloadData_Equal(const PayloadData* pVal1, const PayloadData* pVal2);

#define ERR_PAYLOADDATA_INT_FIELD		11  /*(-2147483648..2147483647)*/
flag PayloadData_int_field_IsConstraintValid(const PayloadData_int_field* pVal, int* pErrCode);

#define ERR_PAYLOADDATA_BUFFER1		16  /*(SIZE(0..100))*/
flag PayloadData_buffer1_IsConstraintValid(const PayloadData_buffer1* pVal, int* pErrCode);

#define ERR_PAYLOADDATA_BUFFER2		21  /*(SIZE(0..100))*/
flag PayloadData_buffer2_IsConstraintValid(const PayloadData_buffer2* pVal, int* pErrCode);

#define ERR_PAYLOADDATA		26  /**/
flag PayloadData_IsConstraintValid(const PayloadData* pVal, int* pErrCode);

void PayloadData_int_field_Initialize(PayloadData_int_field* pVal);
void PayloadData_buffer1_Initialize(PayloadData_buffer1* pVal);
void PayloadData_buffer2_Initialize(PayloadData_buffer2* pVal);
void PayloadData_Initialize(PayloadData* pVal);

#define PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING       204
#define PayloadData_REQUIRED_BITS_FOR_ACN_ENCODING        1632
/*-- Header --------------------------------------------*/
typedef struct {

} Header;

flag Header_Equal(const Header* pVal1, const Header* pVal2);

#define ERR_HEADER		31  /**/
flag Header_IsConstraintValid(const Header* pVal, int* pErrCode);

void Header_Initialize(Header* pVal);

#define Header_REQUIRED_BYTES_FOR_ACN_ENCODING       0
#define Header_REQUIRED_BITS_FOR_ACN_ENCODING        0


flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode);
/*-- PDU --------------------------------------------*/
typedef struct {
    Header hdr;
    PayloadData payload;

} PDU;

flag PDU_Equal(const PDU* pVal1, const PDU* pVal2);

#define ERR_PDU		76  /**/
#define ERR_PDU_HDR_2		73  /**/
#define ERR_PDU_PAYLOAD_2		56  /**/
flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode);

void PDU_Initialize(PDU* pVal);

#define PDU_REQUIRED_BYTES_FOR_ACN_ENCODING       208
#define PDU_REQUIRED_BITS_FOR_ACN_ENCODING        1664

#define ERR_ACN_ENCODE_PDU		79  /**/
#define ERR_ACN_ENCODE_PDU_HDR		71  /**/
#define ERR_ACN_ENCODE_PDU_HDR_VERSION		61  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD		54  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_INT_FIELD		39  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_BUFFER1		44  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_BUFFER2		49  /**/
#define ERR_ACN_ENCODE_PDU_HDR_PDU_LENGTH_UNINITIALIZED		80  /**/
#define ERR_ACN_ENCODE_PDU_HDR_PDU_LENGTH		63  /**/
#define ERR_ACN_ENCODE_UPDATE_PDU_PAYLOAD_BUFFER_LEN		67  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED		81  /**/
#define ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH		65  /**/
#define ERR_ACN_ENCODE_PDU_PAYLOAD_2		59  /**/

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_PDU		82  /**/
#define ERR_ACN_DECODE_PDU_HDR		72  /**/
#define ERR_ACN_DECODE_PDU_HDR_VERSION		62  /**/
#define ERR_ACN_DECODE_PDU_HDR_PDU_LENGTH		64  /**/
#define ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH		66  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_2		60  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD		55  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_INT_FIELD		40  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_BUFFER1		45  /**/
#define ERR_ACN_DECODE_PDU_PAYLOAD_BUFFER2		50  /**/
flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode);


/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */



#ifdef  __cplusplus
}

#endif

#endif
