/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "a.h"


flag BUFFER_LENGTH_TYPE_Equal(const BUFFER_LENGTH_TYPE* pVal1, const BUFFER_LENGTH_TYPE* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag BUFFER_LENGTH_TYPE_IsConstraintValid(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 100UL);
    *pErrCode = ret ? 0 :  ERR_BUFFER_LENGTH_TYPE;

	return ret;
}

void BUFFER_LENGTH_TYPE_Initialize(BUFFER_LENGTH_TYPE* pVal)
{
	(void)pVal;


	(*(pVal)) = 0UL;
}

flag BUFFER_LENGTH_TYPE_ACN_Encode(const BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? BUFFER_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 100);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag BUFFER_LENGTH_TYPE_ACN_Decode(BUFFER_LENGTH_TYPE* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 100);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_BUFFER_LENGTH_TYPE;

    return ret && BUFFER_LENGTH_TYPE_IsConstraintValid(pVal, pErrCode);
}


flag Header_Equal(const Header* pVal1, const Header* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag Header_IsConstraintValid(const Header* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

void Header_Initialize(Header* pVal)
{
	(void)pVal;


}

flag Header_ACN_Encode(const Header* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? Header_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag Header_ACN_Decode(Header* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && Header_IsConstraintValid(pVal, pErrCode);
}


flag PayloadData_int_field_Equal(const PayloadData_int_field* pVal1, const PayloadData_int_field* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag PayloadData_buffer_Equal(const PayloadData_buffer* pVal1, const PayloadData_buffer* pVal2)
{
	return (pVal1->nCount == pVal2->nCount) && (memcmp(pVal1->arr, pVal2->arr, pVal1->nCount) ==0);

}

flag PayloadData_Equal(const PayloadData* pVal1, const PayloadData* pVal2)
{
	flag ret=TRUE;

    ret = PayloadData_int_field_Equal((&(pVal1->int_field)), (&(pVal2->int_field)));
    
    if (ret) {
        ret = PayloadData_buffer_Equal((&(pVal1->buffer)), (&(pVal2->buffer)));
    
    }

	return ret;

}

flag PayloadData_int_field_IsConstraintValid(const PayloadData_int_field* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA_INT_FIELD;

	return ret;
}

flag PayloadData_buffer_IsConstraintValid(const PayloadData_buffer* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = (pVal->nCount <= 100);
    *pErrCode = ret ? 0 :  ERR_PAYLOADDATA_BUFFER;

	return ret;
}

flag PayloadData_IsConstraintValid(const PayloadData* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = PayloadData_int_field_IsConstraintValid((&(pVal->int_field)), pErrCode);
    if (ret) {
        ret = PayloadData_buffer_IsConstraintValid((&(pVal->buffer)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PayloadData_int_field_Initialize(PayloadData_int_field* pVal)
{
	(void)pVal;


	(*(pVal)) = 0LL;
}
void PayloadData_buffer_Initialize(PayloadData_buffer* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 100);
	pVal->nCount = 0;

}
void PayloadData_Initialize(PayloadData* pVal)
{
	(void)pVal;


	/*set int_field */
	PayloadData_int_field_Initialize((&(pVal->int_field)));
	/*set buffer */
	PayloadData_buffer_Initialize((&(pVal->buffer)));
}

flag PayloadData_ACN_Encode(const PayloadData* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? PayloadData_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode int_field */
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->int_field, -2147483648LL, 2147483647LL);
	    if (ret) {
	        /*Encode buffer */
	        BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->buffer.nCount, 0, 100);
	        ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->buffer.arr, pVal->buffer.nCount);
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PayloadData_ACN_Decode(PayloadData* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint nCount;

	/*Decode int_field */
	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, (&(pVal->int_field)), -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOADDATA_INT_FIELD;
	if (ret) {
	    /*Decode buffer */
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 100);
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PAYLOADDATA_BUFFER;
	    pVal->buffer.nCount = (long)nCount;
	    ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->buffer.arr, pVal->buffer.nCount);
	}   /*COVERAGE_IGNORE*/

    return ret && PayloadData_IsConstraintValid(pVal, pErrCode);
}


flag PDU_Equal(const PDU* pVal1, const PDU* pVal2)
{
	flag ret=TRUE;

    ret = Header_Equal((&(pVal1->hdr)), (&(pVal2->hdr)));
    
    if (ret) {
        ret = PayloadData_Equal((&(pVal1->payload)), (&(pVal2->payload)));
    
    }

	return ret;

}

flag PDU_IsConstraintValid(const PDU* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = Header_IsConstraintValid((&(pVal->hdr)), pErrCode);
    if (ret) {
        ret = PayloadData_IsConstraintValid((&(pVal->payload)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void PDU_Initialize(PDU* pVal)
{
	(void)pVal;


	/*set hdr */
	Header_Initialize((&(pVal->hdr)));
	/*set payload */
	PayloadData_Initialize((&(pVal->payload)));
}

flag PDU_ACN_Encode(const PDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint PDU_hdr_buffers_length;
	flag PDU_hdr_buffers_length_is_initialized=FALSE;
    *pErrCode = 0;
	ret = bCheckConstraints ? PDU_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    /*Encode hdr */
	    /*Encode PDU_hdr_version */
	    {
	    	static byte tmp[] = {0x01};
	    	BitStream_AppendBits(pBitStrm, tmp, 8);
	    }
	    if (ret) {
	        PDU_hdr_buffers_length_is_initialized = TRUE;
	        PDU_hdr_buffers_length = pVal->payload.buffer.nCount;
	        if (ret) {
	            /*Encode PDU_hdr_buffers_length */
	            if (PDU_hdr_buffers_length_is_initialized) {
	                ret = TRUE;
	                Acn_Enc_Int_PositiveInteger_ConstSize_8(pBitStrm, PDU_hdr_buffers_length);
	            } else {
	                *pErrCode = ERR_ACN_ENCODE_PDU_HDR_BUFFERS_LENGTH_UNINITIALIZED;         /*COVERAGE_IGNORE*/
	                ret = FALSE;                    /*COVERAGE_IGNORE*/
	            }
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
	    if (ret) {
	        /*Encode payload */
	        /*Encode int_field */
	        Acn_Enc_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, pVal->payload.int_field);
	        if (ret) {
	            /*Encode buffer */
	            ret = BitStream_EncodeOctetString_no_length(pBitStrm, pVal->payload.buffer.arr, pVal->payload.buffer.nCount);
	        }   /*COVERAGE_IGNORE*/
	    }   /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag PDU_ACN_Decode(PDU* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint PDU_hdr_buffers_length;

	/*Decode hdr */
	/*Decode PDU_hdr_version */
	{
		static byte tmp[] = {0x01};
	    flag bDecodingPatternMatches;
		ret = BitStream_ReadBitPattern(pBitStrm, tmp, 8, &bDecodingPatternMatches);
	    ret = ret && bDecodingPatternMatches;
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_VERSION;
	}
	
	if (ret) {
	    /*Decode PDU_hdr_buffers_length */
	    ret = Acn_Dec_Int_PositiveInteger_ConstSize_8(pBitStrm, (&(PDU_hdr_buffers_length)));
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_HDR_BUFFERS_LENGTH;
	}   /*COVERAGE_IGNORE*/
	if (ret) {
	    /*Decode payload */
	    /*Decode int_field */
	    ret = Acn_Dec_Int_TwosComplement_ConstSize_big_endian_32(pBitStrm, (&(pVal->payload.int_field)));
	    *pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_INT_FIELD;
	    if (ret) {
	        /*Decode buffer */
	        ret = ((PDU_hdr_buffers_length<=100));
	        if (ret) {
	            pVal->payload.buffer.nCount = (int)PDU_hdr_buffers_length;
	            ret = BitStream_DecodeOctetString_no_length(pBitStrm, pVal->payload.buffer.arr, pVal->payload.buffer.nCount);
	        	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PDU_PAYLOAD_BUFFER;
	        }
	    }   /*COVERAGE_IGNORE*/
	}   /*COVERAGE_IGNORE*/

    return ret && PDU_IsConstraintValid(pVal, pErrCode);
}


