/*
Code automatically generated by asn1scc tool
*/

#include <string.h>
#include <math.h>
#include <limits.h>
#include <stdio.h>
#include "asn1crt.h"
#include "a_auto_tcs.h"


flag BUFFER_LENGTH_TYPE_ACN_enc_dec(const BUFFER_LENGTH_TYPE* pVal, int* pErrCode, const char* filename)
{
    static BUFFER_LENGTH_TYPE decodedPDU;
    static byte encBuff[BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING + 1]; /* +1 for zerosized types */
    BitStream bitStrm;
    flag ret = TRUE;

    BitStream_Init(&bitStrm, encBuff, BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING);
    // Encode value
    ret = BUFFER_LENGTH_TYPE_ACN_Encode(pVal, &bitStrm, pErrCode, TRUE);
    *pErrCode = (ret && *pErrCode ==0) ? 0 : 1;
    if (ret) {
        BitStream_AttachBuffer(&bitStrm, encBuff, BUFFER_LENGTH_TYPE_REQUIRED_BYTES_FOR_ACN_ENCODING);
        // Decode value
        ret = BUFFER_LENGTH_TYPE_ACN_Decode(&decodedPDU, &bitStrm, pErrCode);
        *pErrCode = (ret && *pErrCode ==0) ? 0 : 2;
        if (ret) {
            // validate decoded data
            ret = BUFFER_LENGTH_TYPE_IsConstraintValid(&decodedPDU, pErrCode);
            *pErrCode = (ret && *pErrCode ==0) ? 0 : 3;
            if (ret) {
                ret = BUFFER_LENGTH_TYPE_Equal(pVal, &decodedPDU);
                *pErrCode = ret ? 0 : 4;
                if (ret) {
                    char buf[1024];
                    strcpy(buf, filename);
                    FILE* fp = fopen(strcat(buf,".dat"), "wb");
                    fwrite(bitStrm.buf, 1, bitStrm.currentBit > 0 ? bitStrm.currentByte + 1 : bitStrm.currentByte, fp);
                    fclose(fp);
                
                }
            
            }
        
        }
    
    }

    return ret;
}
flag PayloadData_ACN_enc_dec(const PayloadData* pVal, int* pErrCode, const char* filename)
{
    static PayloadData decodedPDU;
    static byte encBuff[PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING + 1]; /* +1 for zerosized types */
    BitStream bitStrm;
    flag ret = TRUE;

    BitStream_Init(&bitStrm, encBuff, PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING);
    // Encode value
    ret = PayloadData_ACN_Encode(pVal, &bitStrm, pErrCode, TRUE);
    *pErrCode = (ret && *pErrCode ==0) ? 0 : 1;
    if (ret) {
        BitStream_AttachBuffer(&bitStrm, encBuff, PayloadData_REQUIRED_BYTES_FOR_ACN_ENCODING);
        // Decode value
        ret = PayloadData_ACN_Decode(&decodedPDU, &bitStrm, pErrCode);
        *pErrCode = (ret && *pErrCode ==0) ? 0 : 2;
        if (ret) {
            // validate decoded data
            ret = PayloadData_IsConstraintValid(&decodedPDU, pErrCode);
            *pErrCode = (ret && *pErrCode ==0) ? 0 : 3;
            if (ret) {
                ret = PayloadData_Equal(pVal, &decodedPDU);
                *pErrCode = ret ? 0 : 4;
                if (ret) {
                    char buf[1024];
                    strcpy(buf, filename);
                    FILE* fp = fopen(strcat(buf,".dat"), "wb");
                    fwrite(bitStrm.buf, 1, bitStrm.currentBit > 0 ? bitStrm.currentByte + 1 : bitStrm.currentByte, fp);
                    fclose(fp);
                
                }
            
            }
        
        }
    
    }

    return ret;
}
flag PDU_ACN_enc_dec(const PDU* pVal, int* pErrCode, const char* filename)
{
    static PDU decodedPDU;
    static byte encBuff[PDU_REQUIRED_BYTES_FOR_ACN_ENCODING + 1]; /* +1 for zerosized types */
    BitStream bitStrm;
    flag ret = TRUE;

    BitStream_Init(&bitStrm, encBuff, PDU_REQUIRED_BYTES_FOR_ACN_ENCODING);
    // Encode value
    ret = PDU_ACN_Encode(pVal, &bitStrm, pErrCode, TRUE);
    *pErrCode = (ret && *pErrCode ==0) ? 0 : 1;
    if (ret) {
        BitStream_AttachBuffer(&bitStrm, encBuff, PDU_REQUIRED_BYTES_FOR_ACN_ENCODING);
        // Decode value
        ret = PDU_ACN_Decode(&decodedPDU, &bitStrm, pErrCode);
        *pErrCode = (ret && *pErrCode ==0) ? 0 : 2;
        if (ret) {
            // validate decoded data
            ret = PDU_IsConstraintValid(&decodedPDU, pErrCode);
            *pErrCode = (ret && *pErrCode ==0) ? 0 : 3;
            if (ret) {
                ret = PDU_Equal(pVal, &decodedPDU);
                *pErrCode = ret ? 0 : 4;
                if (ret) {
                    char buf[1024];
                    strcpy(buf, filename);
                    FILE* fp = fopen(strcat(buf,".dat"), "wb");
                    fwrite(bitStrm.buf, 1, bitStrm.currentBit > 0 ? bitStrm.currentByte + 1 : bitStrm.currentByte, fp);
                    fclose(fp);
                
                }
            
            }
        
        }
    
    }

    return ret;
}
