/*  Code automatically generated by asn1scc tool (stg macro : printTestCaseFileBody) */

#include "test_case_001.h"

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <limits.h>

#ifndef _MSC_VER
#include <sys/time.h>

#endif // _MSC_VER

#include "asn1crt.h"

#include "a_auto_tcs.h"

void test_case_ACN_000001(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000001");
    {
        // dummy statement used for calling init functions
BUFFER_LENGTH_TYPE tmp0;
        BUFFER_LENGTH_TYPE_Initialize((&(tmp0)));
    }

BUFFER_LENGTH_TYPE tc_data; 
    tc_data = 0UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000001");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("BUFFER_LENGTH_TYPE/test_case_ACN_000001", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000001");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000001 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000001' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000001'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000002(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;

    output->report_case_begin("test_case_ACN_000002");
    {
        // dummy statement used for calling init functions
BUFFER_LENGTH_TYPE tmp0;
        BUFFER_LENGTH_TYPE_Initialize((&(tmp0)));
    }

BUFFER_LENGTH_TYPE tc_data; 
    tc_data = 100UL;
#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000002");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("BUFFER_LENGTH_TYPE/test_case_ACN_000002", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = BUFFER_LENGTH_TYPE_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000002");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000002 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000002' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000002'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000003(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000003");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set payload */
    /*set int_field */
    tc_data.payload.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.payload.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.payload.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000003");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000003", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000003");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000003 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000003' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000003'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000004(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000004");
    {
        // dummy statement used for calling init functions
        static PDU tmp0;
        PDU_Initialize((&(tmp0)));
    }

    static PDU tc_data; 
    /*set payload */
    /*set int_field */
    tc_data.payload.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.payload.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.payload.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000004");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PDU/test_case_ACN_000004", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PDU_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000004");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000004 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000004' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000004'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000005(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000005");
    {
        // dummy statement used for calling init functions
        static PayloadData tmp0;
        PayloadData_int_field_Initialize((&(tmp0.int_field)));
        PayloadData_buffer_Initialize((&(tmp0.buffer)));
        PayloadData_Initialize((&(tmp0)));
    }

    static PayloadData tc_data; 
    /*set int_field */
    tc_data.int_field = -2147483648LL;
    /*set buffer */
    i1 = 0;
    while (i1< 0) {
        tc_data.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.buffer.nCount = 0;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PayloadData_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000005");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PayloadData/test_case_ACN_000005", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PayloadData_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000005");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000005 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000005' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000005'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}

void test_case_ACN_000006(const TestOutput* output, int *totalErrors)
{
    flag result;
    int errCode;
    int i1;

    output->report_case_begin("test_case_ACN_000006");
    {
        // dummy statement used for calling init functions
        static PayloadData tmp0;
        PayloadData_int_field_Initialize((&(tmp0.int_field)));
        PayloadData_buffer_Initialize((&(tmp0.buffer)));
        PayloadData_Initialize((&(tmp0)));
    }

    static PayloadData tc_data; 
    /*set int_field */
    tc_data.int_field = 2147483647LL;
    /*set buffer */
    i1 = 0;
    while (i1< 100) {
        tc_data.buffer.arr[i1] = (byte)(i1%256);
        i1 = i1 + 1;
    }
    tc_data.buffer.nCount = 100;

#ifndef _MSC_VER
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    result = PayloadData_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000006");
    gettimeofday(&stop, NULL);
    if (result) {
        output->report_test_case_success("PayloadData/test_case_ACN_000006", ((stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec)/1000);
    } else {
#else
    result = PayloadData_ACN_enc_dec(&tc_data, &errCode, "test_case_ACN_000006");
    if (!result) {
#endif

        output->report_failure_begin();

        switch(errCode)
        {
        case 1:
            output->report_failure_message("Test case test_case_ACN_000006 failed in encoding.");
            break;
        case 2:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed in decoding.");
            break;
        case 3:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed in the validation of the decoded message.");
            break;
        case 4:
            output->report_failure_message("Test case 'test_case_ACN_000006' failed. Encoded and decoded messages are different.");
            break;
        default:
            output->report_failure_message("Unexpected error code in test case 'test_case_ACN_000006'.");
        }
        output->report_failure_message("========================================");
        *totalErrors = (*totalErrors) + 1;

        output->report_failure_end();
    }

    output->report_case_end();
}
